/*
CREATE THE TRM EVENT TABLES

- PROCEDURE
- OBSERVATION
- CONDITION
- MEASUREMENT 
- DRUG 
- DEVICE

*/



-- CREATE TRM.MEASUREMENT
DROP TABLE IF EXISTS TRM.MEASUREMENT;
CREATE TABLE TRM.MEASUREMENT (
    MEASUREMENT_ID BIGINT NOT NULL IDENTITY(1,1)
    ,PERSON_ID BIGINT NOT NULL
    ,MEASUREMENT_CONCEPT_ID INTEGER NOT NULL
    ,MEASUREMENT_DATE DATE NULL
    ,MEASUREMENT_DATETIME DATETIME2 NOT NULL
    ,MEASUREMENT_TIME VARCHAR(10) NULL
    ,MEASUREMENT_TYPE_CONCEPT_ID INTEGER NOT NULL
    ,OPERATOR_CONCEPT_ID INTEGER NULL
    ,VALUE_AS_NUMBER FLOAT NULL
    ,VALUE_AS_CONCEPT_ID INTEGER NULL
    ,UNIT_CONCEPT_ID INTEGER NULL
    ,RANGE_LOW FLOAT NULL
    ,RANGE_HIGH FLOAT NULL
    ,PROVIDER_ID BIGINT NULL
    ,VISIT_OCCURRENCE_ID BIGINT NULL
    ,VISIT_DETAIL_ID BIGINT NULL
    ,MEASUREMENT_SOURCE_VALUE VARCHAR(50) NULL
    ,MEASUREMENT_SOURCE_CONCEPT_ID INTEGER NOT NULL
    ,UNIT_SOURCE_VALUE VARCHAR(50) NULL
    ,VALUE_SOURCE_VALUE VARCHAR(50) NULL
    ,SOURCE VARCHAR(20)
);
GO 

-- CREATE TRM.OBSERVATION 
DROP TABLE IF EXISTS TRM.OBSERVATION;
CREATE TABLE TRM.OBSERVATION (
    OBSERVATION_ID BIGINT NOT NULL IDENTITY(1,1)
    ,PERSON_ID BIGINT NOT NULL
    ,OBSERVATION_CONCEPT_ID INTEGER NOT NULL
    ,OBSERVATION_DATE DATE NULL
    ,OBSERVATION_DATETIME DATETIME2 NOT NULL
    ,OBSERVATION_TYPE_CONCEPT_ID INTEGER NOT NULL
    ,VALUE_AS_NUMBER FLOAT NULL
    ,VALUE_AS_STRING VARCHAR(60) NULL
    ,VALUE_AS_CONCEPT_ID INTEGER NULL
    ,QUALIFIER_CONCEPT_ID INTEGER NULL
    ,UNIT_CONCEPT_ID INTEGER NULL
    ,PROVIDER_ID INTEGER NULL
    ,VISIT_OCCURRENCE_ID BIGINT NULL
    ,VISIT_DETAIL_ID BIGINT NULL
    ,OBSERVATION_SOURCE_VALUE VARCHAR(50) NULL
    ,OBSERVATION_SOURCE_CONCEPT_ID INTEGER NOT NULL
    ,UNIT_SOURCE_VALUE VARCHAR(50) NULL
    ,QUALIFIER_SOURCE_VALUE VARCHAR(50) NULL
    ,OBSERVATION_EVENT_ID BIGINT NULL 
    ,OBS_EVENT_FIELD_CONCEPT_ID INTEGER NOT NULL
    ,VALUE_AS_DATETIME DATETIME2 NULL
    ,SOURCE VARCHAR(20)
);
GO

-- CREATE TRM.PROCEDURE_OCCURRENCE TABLE
-- DATA FROM MULTIPLE SOURCE TABLES WILL FEED INTO THIS TABLE
DROP TABLE IF EXISTS TRM.PROCEDURE_OCCURRENCE;
CREATE TABLE TRM.PROCEDURE_OCCURRENCE (
    PROCEDURE_OCCURRENCE_ID BIGINT NOT NULL IDENTITY(1,1)
    ,PERSON_ID BIGINT NOT NULL
    ,PROCEDURE_CONCEPT_ID INTEGER NOT NULL
    ,PROCEDURE_DATE DATE NULL
    ,PROCEDURE_DATETIME DATETIME2 NOT NULL
    ,PROCEDURE_TYPE_CONCEPT_ID INTEGER NOT NULL
    ,MODIFIER_CONCEPT_ID INTEGER NOT NULL
    ,QUANTITY INTEGER NULL
    ,PROVIDER_ID BIGINT NULL
    ,VISIT_OCCURRENCE_ID BIGINT NULL
    ,VISIT_DETAIL_ID BIGINT NULL
    ,PROCEDURE_SOURCE_VALUE VARCHAR(50) NULL
    ,PROCEDURE_SOURCE_CONCEPT_ID INTEGER NOT NULL
    ,MODIFIER_SOURCE_VALUE VARCHAR(50) NULL
    ,SOURCE VARCHAR(20) NOT NULL
);
GO

-- CREATE TRM.CONDITION_OCCURRENCE TABLE
-- DATA FROM MULTIPLE SOURCE TABLES WILL FEED INTO THIS TABLE
DROP TABLE IF EXISTS TRM.CONDITION_OCCURRENCE
CREATE TABLE TRM.CONDITION_OCCURRENCE (
    CONDITION_OCCURRENCE_ID BIGINT NOT NULL IDENTITY(1, 1) -- AUTO INCRMEMENT
    ,PERSON_ID BIGINT NOT NULL
    ,CONDITION_CONCEPT_ID INTEGER NOT NULL
    ,CONDITION_START_DATE DATE NULL
    ,CONDITION_START_DATETIME DATETIME2 NOT NULL
    ,CONDITION_END_DATE DATE NULL
    ,CONDITION_END_DATETIME DATETIME2 NULL
    ,CONDITION_TYPE_CONCEPT_ID INTEGER NOT NULL
    ,CONDITION_STATUS_CONCEPT_ID INTEGER NOT NULL
    ,STOP_REASON VARCHAR(20) NULL
    ,PROVIDER_ID BIGINT NULL
    ,VISIT_OCCURRENCE_ID BIGINT NULL
    ,VISIT_DETAIL_ID BIGINT NULL
    ,CONDITION_SOURCE_VALUE VARCHAR(50) NULL
    ,CONDITION_SOURCE_CONCEPT_ID INTEGER NOT NULL
    ,CONDITION_STATUS_SOURCE_VALUE VARCHAR(50) NULL
    ,SOURCE VARCHAR(20) NOT NULL
);
-- CONDITION STATUS IS SUPPOSED TO BE THE POINT OF CARE?? NOT SURE WHAT TO USE THERE.
GO


-- CREATE TRM.DRUG_EXPOSURE TABLE
-- DATA FROM MULTIPLE SOURCE TABLES WILL FEED INTO THIS TABLE
DROP TABLE IF EXISTS TRM.DRUG_EXPOSURE
CREATE TABLE TRM.DRUG_EXPOSURE (
    DRUG_EXPOSURE_ID BIGINT NOT NULL IDENTITY(1, 1) -- AUTO INCRMEMENT
    ,PERSON_ID BIGINT NOT NULL
    ,DRUG_CONCEPT_ID INTEGER NOT NULL
    ,DRUG_EXPOSURE_START_DATE DATE NULL
    ,DRUG_EXPOSURE_START_DATETIME DATETIME2 NOT NULL
    ,DRUG_EXPOSURE_END_DATE DATE NULL
    ,DRUG_EXPOSURE_END_DATETIME DATETIME2 NOT NULL
    ,VERBATIM_END_DATE DATE NULL
    ,DRUG_TYPE_CONCEPT_ID INTEGER NOT NULL
    ,STOP_REASON VARCHAR(20) NULL
    ,REFILLS INTEGER NULL
    ,QUANTITY FLOAT NULL
    ,DAYS_SUPPLY INTEGER NULL
    ,SIG VARCHAR(MAX) NULL
    ,ROUTE_CONCEPT_ID INTEGER NOT NULL
    ,LOT_NUMBER VARCHAR(50) NULL
    ,PROVIDER_ID BIGINT NULL
    ,VISIT_OCCURRENCE_ID BIGINT NULL
    ,VISIT_DETAIL_ID BIGINT NULL
    ,DRUG_SOURCE_VALUE VARCHAR(50) NULL
    ,DRUG_SOURCE_CONCEPT_ID INTEGER NOT NULL
    ,ROUTE_SOURCE_VALUE VARCHAR(50) NULL
    ,DOSE_UNIT_SOURCE_VALUE VARCHAR(50) NULL
    ,SOURCE VARCHAR(20) NOT NULL
);
GO

--CREATE TRM.DEVICE_EXPOSURE TABLE
DROP TABLE IF EXISTS TRM.DEVICE_EXPOSURE;
CREATE TABLE TRM.DEVICE_EXPOSURE (
    DEVICE_EXPOSURE_ID BIGINT NOT NULL IDENTITY(1, 1) 
    ,PERSON_ID BIGINT NOT NULL
    ,DEVICE_CONCEPT_ID INTEGER NOT NULL
    ,DEVICE_EXPOSURE_START_DATE DATE NULL
    ,DEVICE_EXPOSURE_START_DATETIME DATETIME2 NOT NULL
    ,DEVICE_EXPOSURE_END_DATE DATE NULL
    ,DEVICE_EXPOSURE_END_DATETIME DATETIME2 NULL
    ,DEVICE_TYPE_CONCEPT_ID INTEGER NOT NULL
    ,UNIQUE_DEVICE_ID VARCHAR(50) NULL
    ,QUANTITY INTEGER NULL
    ,PROVIDER_ID BIGINT NULL
    ,VISIT_OCCURRENCE_ID BIGINT NULL
    ,VISIT_DETAIL_ID BIGINT NULL
    ,DEVICE_SOURCE_VALUE VARCHAR(100) NULL
    ,DEVICE_SOURCE_CONCEPT_ID INTEGER NOT NULL
    ,SOURCE VARCHAR(20) NOT NULL
);


