/*
MAP THE NDC CODES INTO OMOP

THERE ARE TWO SOURCES FOR NDC CODES
    THE PHARMACY CLAIMS
    THE MEDICAL CLAIMS

THERE ARE TWO TARGET TABLES FOR NDC CODE
    DRUG EXPOSURE
    DEVICE EXPOSURE

*/

-- GET ALL NDC CODES IN SOURCE DATA
DROP TABLE IF EXISTS ##NDC_CODES;
SELECT DISTINCT A.NDC
INTO ##NDC_CODES
FROM (
    SELECT DISTINCT NDC FROM STG.MC WHERE NDC IS NOT NULL
    UNION
    SELECT DISTINCT NDC FROM STG.PC WHERE NDC IS NOT NULL
) A
;
GO


-- CREATE NDC_MAP CROSSWALK TABLE (SOURCE TO STANDARD MAP)
DROP TABLE IF EXISTS  ##NDC_MAP;
-- Get ICD codes
WITH T1 AS(
SELECT --TOP 10
    -- VOCABULARY_ID AS SOURCE_VOCABULARY_ID,
    CONCEPT_CODE AS SOURCE_CONCEPT_CODE,
    CONCEPT_ID AS SOURCE_CONCEPT_ID
FROM CDM.CONCEPT
WHERE VOCABULARY_ID = 'NDC'
),
-- Get the standard condtion concepts
T2 AS(
    SELECT T1.*,
        RELATIONSHIP_ID,
        CR.CONCEPT_ID_2 AS TARGET_CONCEPT_ID
    FROM T1
    INNER JOIN CDM.CONCEPT_RELATIONSHIP CR
    ON T1.SOURCE_CONCEPT_ID = CR.CONCEPT_ID_1
    WHERE RELATIONSHIP_ID = 'Maps to' -- DO WE NEED TO INCLUDE 'MAPS TO VALUE'?
),
-- Get the concept info for the standard concepts
T3 AS(
    SELECT *
    FROM T2
    INNER JOIN CDM.CONCEPT C
        ON T2.TARGET_CONCEPT_ID = C.CONCEPT_ID
)
SELECT
    NDC,
    COALESCE(CONCEPT_ID, 0) AS DRUG_CONCEPT_ID,
    -- DEFAULT DOMAIN FOR DX CODES IS CONDITION DOMAIN
    COALESCE(DOMAIN_ID, 'Drug') AS DOMAIN_ID,
    NDC AS DRUG_SOURCE_VALUE,
    COALESCE(SOURCE_CONCEPT_ID, 0) AS DRUG_SOURCE_CONCEPT_ID
INTO ##NDC_MAP
FROM ##NDC_CODES SOURCE_NDC
LEFT JOIN T3
ON SOURCE_NDC.NDC = T3.SOURCE_CONCEPT_CODE;
GO


/*
WHICH DOMAINS TO NDC CODES MAP TO?
SELECT DISTINCT DOMAIN_ID FROM ##NDC_MAP

DEVICE AND DRUG

*/


-- GET A MHDO_CLAIM TO VISIT ID CROSSWALK
DROP TABLE IF EXISTS ##MHDO_CLAIM_VISIT_ID_CROSSWALK;
SELECT DISTINCT
    MHDO_CLAIM
    ,VISIT_OCCURRENCE_ID
INTO ##MHDO_CLAIM_VISIT_ID_CROSSWALK
FROM TRM.VISIT_DETAIL
GO

-- COMBINE NDC DATA FROM BOTH SOURCE TABLES (MC AND PC)
DROP TABLE IF EXISTS ##TRM_NDC;
WITH T1 AS(
SELECT --TOP 100
    A.PATKEY AS PERSON_ID
    ,B.DRUG_CONCEPT_ID
    ,TRY_CAST(A.FDATE AS DATE) AS DRUG_EXPOSURE_START_DATE
    ,TRY_CAST(A.FDATE AS DATETIME2) AS DRUG_EXPOSURE_START_DATETIME
    ,TRY_CAST(DATEADD(DAY, 1, A.FDATE) AS DATE) AS DRUG_EXPOSURE_END_DATE
    ,TRY_CAST(DATEADD(DAY, 1, A.FDATE) AS DATETIME2) AS DRUG_EXPOSURE_END_DATETIME
    ,CAST(NULL AS DATE) AS VERBATIM_END_DATE
    ,0 AS DRUG_TYPE_CONCEPT_ID -- NO CONCEPT ID FOR PHARMACY CLAIM
    ,CAST(NULL AS VARCHAR(20)) AS STOP_REASON
    ,CAST(NULL AS INTEGER) AS REFILLS
    ,CAST(NULL AS FLOAT) AS QUANTITY
    ,CAST(NULL AS INTEGER) AS DAYS_SUPPLY
    ,CAST(NULL AS VARCHAR(MAX)) AS SIG
    ,0 AS ROUTE_CONCEPT_ID
    ,CAST(NULL AS VARCHAR(50)) AS LOT_NUMBER
    ,CAST(
        COALESCE(
            CASE WHEN A.ATT_NPI IN(SELECT PROVIDER_ID FROM CDM.PROVIDER) THEN A.ATT_NPI ELSE NULL END
            ,CASE WHEN A.SERVICING_NPI IN(SELECT PROVIDER_ID FROM CDM.PROVIDER) THEN A.SERVICING_NPI ELSE NULL END
            ,CASE WHEN A.OP_NPI IN(SELECT PROVIDER_ID FROM CDM.PROVIDER) THEN A.OP_NPI ELSE NULL END
            ,CASE WHEN A.NPI IN(SELECT PROVIDER_ID FROM CDM.PROVIDER) THEN A.NPI ELSE NULL END
        )
    AS BIGINT) AS PROVIDER_ID
    ,C.VISIT_OCCURRENCE_ID
    ,NULL AS VISIT_DETAIL_ID
    ,B.DRUG_SOURCE_VALUE
    ,B.DRUG_SOURCE_CONCEPT_ID
    ,NULL AS ROUTE_SOURCE_VALUE
    ,NULL AS DOSE_UNIT_SOURCE_VALUE
    ,'STG.MC.NDC' AS SOURCE
    ,B.DOMAIN_ID
FROM STG.MC A
JOIN ##NDC_MAP B
ON A.NDC = B.NDC
JOIN ##MHDO_CLAIM_VISIT_ID_CROSSWALK C
ON A.MHDO_CLAIM = C.MHDO_CLAIM
)
,T2 AS(
-- DEFAULT DAYS SUPPLY TO 1 DAY IF IT IS NULL
SELECT --TOP 100
    A.PATKEY AS PERSON_ID
    ,B.DRUG_CONCEPT_ID
    ,TRY_CAST(A.FDATE AS DATE) AS DRUG_EXPOSURE_START_DATE
    ,TRY_CAST(A.FDATE AS DATETIME2) AS DRUG_EXPOSURE_START_DATETIME
    ,TRY_CAST(DATEADD(DAY, COALESCE(A.DAYS, 1), A.FDATE) AS DATE) AS DRUG_EXPOSURE_END_DATE
    ,TRY_CAST(DATEADD(DAY, COALESCE(A.DAYS, 1), A.FDATE) AS DATETIME2) AS DRUG_EXPOSURE_END_DATETIME
    ,CAST(NULL AS DATE) AS VERBATIM_END_DATE
    ,0 AS DRUG_TYPE_CONCEPT_ID -- NO CONCEPT ID FOR PHARMACY CLAIM
    ,CAST(NULL AS VARCHAR(20)) AS STOP_REASON
    ,CAST(NULL AS INTEGER) AS REFILLS
    ,TRY_CAST(QTY AS FLOAT) AS QUANTITY
    ,TRY_CAST(DAYS AS INTEGER) AS DAYS_SUPPLY
    ,CAST(NULL AS VARCHAR(MAX)) AS SIG
    ,0 AS ROUTE_CONCEPT_ID
    ,CAST(NULL AS VARCHAR(50)) AS LOT_NUMBER
    ,CAST(PRESCRIBING_NPI AS BIGINT) AS PROVIDER_ID
    ,CAST(NULL AS BIGINT) AS VISIT_OCCURRENCE_ID
    ,CAST(NULL AS BIGINT) AS VISIT_DETAIL_ID
    ,B.DRUG_SOURCE_VALUE
    ,B.DRUG_SOURCE_CONCEPT_ID
    ,CAST(NULL AS VARCHAR(50)) AS ROUTE_SOURCE_VALUE
    ,CAST(NULL AS VARCHAR(50)) AS DOSE_UNIT_SOURCE_VALUE
    ,'STG.PC.NDC' AS SOURCE
    ,B.DOMAIN_ID
FROM STG.PC A
JOIN ##NDC_MAP B
ON A.NDC = B.NDC
)
,T3 AS(
    SELECT * FROM T1
    UNION
    SELECT * FROM T2
)
SELECT *
INTO ##TRM_NDC
FROM T3
GO

/*
-- LOAD THE DATA INTO TARGET TABLES

-- SELECT * FROM ##TRM_NDC


-- COMPARE COUNTS OF SOURCE TO TARGET
SELECT COUNT(*) FROM STG.MC WHERE NDC IS NOT NULL
SELECT COUNT(*) FROM STG.PC WHERE NDC IS NOT NULL
SELECT COUNT(*) FROM ##TRM_NDC
-- NOT SURE WHY WE ARE DROPPING RECORDS...
*/



-- LOAD NDC RECORDS INTO TRM.DRUG_EXPOSURE
DELETE FROM TRM.DRUG_EXPOSURE WHERE SOURCE IN('STG.PC.NDC', 'STG.MC.NDC');
INSERT INTO TRM.DRUG_EXPOSURE
SELECT
    PERSON_ID
    ,DRUG_CONCEPT_ID
    ,DRUG_EXPOSURE_START_DATE
    ,DRUG_EXPOSURE_START_DATETIME
    ,DRUG_EXPOSURE_END_DATE
    ,DRUG_EXPOSURE_END_DATETIME
    ,VERBATIM_END_DATE
    ,DRUG_TYPE_CONCEPT_ID
    ,STOP_REASON
    ,REFILLS
    ,QUANTITY
    ,DAYS_SUPPLY
    ,SIG
    ,ROUTE_CONCEPT_ID
    ,LOT_NUMBER
    ,PROVIDER_ID
    ,VISIT_OCCURRENCE_ID
    ,VISIT_DETAIL_ID
    ,DRUG_SOURCE_VALUE
    ,DRUG_SOURCE_CONCEPT_ID
    ,ROUTE_SOURCE_VALUE
    ,DOSE_UNIT_SOURCE_VALUE
    ,SOURCE
FROM ##TRM_NDC
WHERE DOMAIN_ID = 'Drug';
GO


-- LOAD NDC RECORDS INTO TRM.DEVICE_EXPOSURE
DELETE FROM TRM.DEVICE_EXPOSURE WHERE SOURCE IN('STG.PC.NDC', 'STG.MC.NDC');
INSERT INTO TRM.DEVICE_EXPOSURE
SELECT
    PERSON_ID
    ,DRUG_CONCEPT_ID AS DEVICE_CONCEPT_ID
    ,DRUG_EXPOSURE_START_DATE AS DEVICE_EXPOSURE_START_DATE
    ,DRUG_EXPOSURE_START_DATETIME AS DEVICE_EXPOSURE_START_DATETIME
    ,DRUG_EXPOSURE_END_DATE AS DEVICE_EXPOSURE_END_DATE
    ,DRUG_EXPOSURE_END_DATETIME AS DEVICE_EXPOSURE_END_DATETIME
    ,32465 AS DEVICE_TYPE_CONCEPT_ID -- 32465 = Inferred from claim
    ,CAST(NULL AS VARCHAR(50)) AS UNIQUE_DEVICE_ID
    ,QUANTITY
    ,PROVIDER_ID
    ,VISIT_OCCURRENCE_ID
    ,VISIT_DETAIL_ID
    ,DRUG_SOURCE_VALUE AS DEVICE_SOURCE_VALUE
    ,DRUG_SOURCE_CONCEPT_ID AS DEVICE_SOURCE_CONCEPT_ID
    ,SOURCE
FROM ##TRM_NDC
WHERE DOMAIN_ID = 'Device';
GO


-- DROP TEMP TABLES FOR NDC MAPPING
DROP TABLE IF EXISTS ##NDC_CODES;
DROP TABLE IF EXISTS ##NDC_MAP;
DROP TABLE IF EXISTS ##TRM_NDC;
DROP TABLE IF EXISTS ##MHDO_CLAIM_VISIT_ID_CROSSWALK;

