/***********************
  params: database
***********************/

  --Select database
USE @database@;
GO

-- CREATE RAW.MC_FILEID_PAYERTYPE
DROP TABLE IF EXISTS RAW.MC_FILEID_PAYERTYPE;
CREATE TABLE RAW.MC_FILEID_PAYERTYPE (
  MC906_FILEID VARCHAR(20)
  ,PAYER_TYPE VARCHAR(20)
);
GO

-- CREATE RAW.ME_FILEID_PAYERTYPE
DROP TABLE IF EXISTS RAW.ME_FILEID_PAYERTYPE;
CREATE TABLE RAW.ME_FILEID_PAYERTYPE (
  ME906_FILEID VARCHAR(20)
  ,PAYER_TYPE VARCHAR(20)
);
GO

-- CREATE RAW.PC_FILEID_PAYERTYPE
DROP TABLE IF EXISTS RAW.PC_FILEID_PAYERTYPE;
CREATE TABLE RAW.PC_FILEID_PAYERTYPE (
  PC905_FILEID VARCHAR(20)
  ,PAYER_TYPE VARCHAR(20)
);
GO

-- CREATE RAW.PE_FILEID_PAYERTYPE
DROP TABLE IF EXISTS RAW.PE_FILEID_PAYERTYPE;
CREATE TABLE RAW.PE_FILEID_PAYERTYPE (
  PE906_FILEID VARCHAR(20)
  ,PAYER_TYPE VARCHAR(20)
);
GO

