/*

REMOVE DUPLICATE ROWS FROM THE FILEID_PAYERTYPE LOOKUP TABLES

*/

-- REMOVE DUPLICATE ROWS FROM ME_FILEID_PAYERTYPE 
WITH CTE AS (
    SELECT 
        ME906_FILEID, 
        PAYER_TYPE,
        ROW_NUMBER() OVER (
            PARTITION BY ME906_FILEID, PAYER_TYPE 
            ORDER BY ME906_FILEID, PAYER_TYPE 
        ) ROW_NUM
    FROM 
    RAW.ME_FILEID_PAYERTYPE 
)
DELETE FROM CTE
WHERE ROW_NUM > 1;
GO 

-- VERIFY THAT THERE IS ONE ROW PER FILEID
-- SHOULD THIS BE A FORMAL CHECK?
SELECT N_ROWS, COUNT(*) AS N_PRIMARY_KEY_VALUES
FROM (
    SELECT ME906_FILEID, COUNT(*) AS N_ROWS
    FROM RAW.ME_FILEID_PAYERTYPE 
    GROUP BY ME906_FILEID
) A
GROUP BY N_ROWS;
GO

-- REMOVE DUPLICATE ROWS FROM MC_FILEID_PAYERTYPE
WITH CTE AS (
    SELECT 
        MC906_FILEID, 
        PAYER_TYPE,
        ROW_NUMBER() OVER (
            PARTITION BY MC906_FILEID, PAYER_TYPE 
            ORDER BY MC906_FILEID, PAYER_TYPE 
        ) ROW_NUM
    FROM 
    RAW.MC_FILEID_PAYERTYPE 
)
DELETE FROM CTE
WHERE ROW_NUM > 1;
GO 

-- VERIFY THAT THERE IS ONE ROW PER FILEID
SELECT N_ROWS, COUNT(*) AS N_PRIMARY_KEY_VALUES
FROM (
    SELECT MC906_FILEID, COUNT(*) AS N_ROWS
    FROM RAW.MC_FILEID_PAYERTYPE 
    GROUP BY MC906_FILEID
) A
GROUP BY N_ROWS;
GO



-- REMOVE DUPLICATE ROWS FROM PE_FILEID_PAYERTYPE 
WITH CTE AS (
    SELECT 
        PE906_FILEID, 
        PAYER_TYPE,
        ROW_NUMBER() OVER (
            PARTITION BY PE906_FILEID, PAYER_TYPE 
            ORDER BY PE906_FILEID, PAYER_TYPE 
        ) ROW_NUM
    FROM 
    RAW.PE_FILEID_PAYERTYPE 
)
DELETE FROM CTE
WHERE ROW_NUM > 1;
GO 

-- VERIFY THAT THERE IS ONE ROW PER FILEID
SELECT N_ROWS, COUNT(*) AS N_PRIMARY_KEY_VALUES
FROM (
    SELECT PE906_FILEID, COUNT(*) AS N_ROWS
    FROM RAW.PE_FILEID_PAYERTYPE 
    GROUP BY PE906_FILEID
) A
GROUP BY N_ROWS;
GO

-- REMOVE DUPLICATE ROWS FROM PC_FILEID_PAYERTYPE 
WITH CTE AS (
    SELECT 
        PC905_FILEID, 
        PAYER_TYPE,
        ROW_NUMBER() OVER (
            PARTITION BY PC905_FILEID, PAYER_TYPE 
            ORDER BY PC905_FILEID, PAYER_TYPE 
        ) ROW_NUM
    FROM 
    RAW.PC_FILEID_PAYERTYPE 
)
DELETE FROM CTE
WHERE ROW_NUM > 1;
GO 

-- VERIFY THAT THERE IS ONE ROW PER FILEID
SELECT N_ROWS, COUNT(*) AS N_PRIMARY_KEY_VALUES
FROM (
    SELECT PC905_FILEID, COUNT(*) AS N_ROWS
    FROM RAW.PC_FILEID_PAYERTYPE 
    GROUP BY PC905_FILEID
) A
GROUP BY N_ROWS;
GO

