 /*

 INSERT RECORDS INTO THE VISIT DETAIL TABLE FROM TRM.VISIT_DETAIL
 
 DEPENDENCIES: TRM.VISIT_DETAIL


 */

-- POPULATE CDM.VISIT_DETAIL WITH RECORDS FROM TRM.VISIT_DETAIL
TRUNCATE TABLE CDM.VISIT_DETAIL;
INSERT INTO CDM.VISIT_DETAIL
SELECT --TOP 100
    VISIT_DETAIL_ID 
    ,PERSON_ID 
    ,COALESCE(VISIT_DETAIL_CONCEPT_ID, 0) AS VISIT_DETAIL_CONCEPT_ID 
    ,TRY_CAST(FDATE AS DATE) AS VISIT_DETAIL_START_DATE
    ,TRY_CAST(FDATE AS DATETIME2) AS VISIT_DETAIL_START_DATETIME
    ,TRY_CAST(LDATE AS DATE) AS VISIT_DETAIL_END_DATE
    ,TRY_CAST(LDATE AS DATETIME2) AS VISIT_DETAIL_END_DATETIME
    ,COALESCE(VISIT_DETAIL_TYPE_CONCEPT_ID, 0) AS VISIT_DETAIL_TYPE_CONCEPT_ID 
    ,PROVIDER_ID 
    ,CARE_SITE_ID 
    ,CONCAT(VISIT_DETAIL_SOURCE_VOCABULARY, ' | ', VISIT_DETAIL_SOURCE_VALUE) AS VISIT_DETAIL_SOURCE_VALUE
    ,COALESCE(VISIT_DETAIL_SOURCE_CONCEPT_ID, 0) AS VISIT_DETAIL_SOURCE_CONCEPT_ID
    ,ADMITTED_FROM_SOURCE_VALUE
    ,COALESCE(ADMITTED_FROM_CONCEPT_ID, 0) AS ADMITTED_FROM_CONCEPT_ID 
    ,DISCHARGE_TO_SOURCE_VALUE
    ,COALESCE(DISCHARGE_TO_CONCEPT_ID, 0) AS DISCHARGE_TO_CONCEPT_ID 
    ,CAST(NULL AS INTEGER) AS PRECEDING_VISIT_DETAIL_ID 
    ,CAST(NULL AS INTEGER) AS VISIT_DETAIL_PARENT_ID 
    ,VISIT_OCCURRENCE_ID 
    ,ORGANIZATION_ID    
FROM TRM.VISIT_DETAIL;

-- SELECT TOP 100 * FROM CDM.visit_detail ORDER BY PERSON_ID, VISIT_DETAIL_ID, VISIT_DETAIL_START_DATE

GO

/*
-- CHECK THAT THE NUMBER OF SOURCE AND TARGET RECORDS MATCH
-- MAKE THIS A FORMAL VALIDATION?
SELECT COUNT(*) FROM CDM.visit_detail;
SELECT COUNT(*) FROM TRM.VISIT_DETAIL;

-- CHECK THAT THERE IS ONE ROW PER VISIT_DETAIL_ID IN CDM.VISIT_DETAIL
*/
