

/*
POPULATE THE CDM EVENT TABLES WITH THE TRM EVENT TABLES

EVENT TABLES ARE:
- MEASUREMENT 
- OBSERVATION
- PROCEDURE
- CONDITION
- DRUG 
- DEVICE

*/



-- POPULATE CDM.MEASUREMENT WITH TRM.MEASUREMENT
TRUNCATE TABLE CDM.MEASUREMENT;
INSERT INTO CDM.MEASUREMENT
SELECT 
    MEASUREMENT_ID
    ,PERSON_ID 
    ,MEASUREMENT_CONCEPT_ID 
    ,MEASUREMENT_DATE 
    ,MEASUREMENT_DATETIME   
    ,MEASUREMENT_TIME
    ,MEASUREMENT_TYPE_CONCEPT_ID   
    ,OPERATOR_CONCEPT_ID  
    ,VALUE_AS_NUMBER  
    ,VALUE_AS_CONCEPT_ID  
    ,UNIT_CONCEPT_ID  
    ,RANGE_LOW  
    ,RANGE_HIGH  
    ,PROVIDER_ID  
    ,VISIT_OCCURRENCE_ID  
    ,VISIT_DETAIL_ID  
    ,MEASUREMENT_SOURCE_VALUE
    ,MEASUREMENT_SOURCE_CONCEPT_ID   
    ,UNIT_SOURCE_VALUE 
    ,VALUE_SOURCE_VALUE
FROM TRM.MEASUREMENT;
GO 


-- POPULATE CDM.OBSERVATION WITH TRM.OBSERVATION
TRUNCATE TABLE CDM.OBSERVATION;
INSERT INTO CDM.OBSERVATION
SELECT
    OBSERVATION_ID   
    ,PERSON_ID   
    ,OBSERVATION_CONCEPT_ID   
    ,OBSERVATION_DATE 
    ,OBSERVATION_DATETIME   
    ,OBSERVATION_TYPE_CONCEPT_ID   
    ,VALUE_AS_NUMBER  
    ,VALUE_AS_STRING 
    ,VALUE_AS_CONCEPT_ID  
    ,QUALIFIER_CONCEPT_ID  
    ,UNIT_CONCEPT_ID  
    ,PROVIDER_ID  
    ,VISIT_OCCURRENCE_ID  
    ,VISIT_DETAIL_ID  
    ,OBSERVATION_SOURCE_VALUE 
    ,OBSERVATION_SOURCE_CONCEPT_ID   
    ,UNIT_SOURCE_VALUE 
    ,QUALIFIER_SOURCE_VALUE 
    ,OBSERVATION_EVENT_ID   
    ,OBS_EVENT_FIELD_CONCEPT_ID   
    ,VALUE_AS_DATETIME  
FROM TRM.OBSERVATION;
GO
  
-- POPULATE CDM.PROCEDURE_OCCURRENCE WITH TRM.PROCEDURE_OCCURRENCE
TRUNCATE TABLE CDM.PROCEDURE_OCCURRENCE;
INSERT INTO CDM.PROCEDURE_OCCURRENCE
SELECT
    PROCEDURE_OCCURRENCE_ID    
    ,PERSON_ID   
    ,PROCEDURE_CONCEPT_ID   
    ,PROCEDURE_DATE 
    ,PROCEDURE_DATETIME   
    ,PROCEDURE_TYPE_CONCEPT_ID   
    ,MODIFIER_CONCEPT_ID   
    ,QUANTITY  
    ,PROVIDER_ID  
    ,VISIT_OCCURRENCE_ID  
    ,VISIT_DETAIL_ID  
    ,PROCEDURE_SOURCE_VALUE 
    ,PROCEDURE_SOURCE_CONCEPT_ID   
    ,MODIFIER_SOURCE_VALUE  
FROM TRM.PROCEDURE_OCCURRENCE;
GO

-- POPULATE CDM.CONDITION_OCCURRENCE WITH TRM.CONDITION_OCCURRENCE
TRUNCATE TABLE CDM.CONDITION_OCCURRENCE;
INSERT INTO CDM.CONDITION_OCCURRENCE
SELECT
    CONDITION_OCCURRENCE_ID   
    ,PERSON_ID   
    ,CONDITION_CONCEPT_ID   
    ,CONDITION_START_DATE 
    ,CONDITION_START_DATETIME   
    ,CONDITION_END_DATE 
    ,CONDITION_END_DATETIME  
    ,CONDITION_TYPE_CONCEPT_ID   
    ,CONDITION_STATUS_CONCEPT_ID   
    ,STOP_REASON 
    ,PROVIDER_ID  
    ,VISIT_OCCURRENCE_ID  
    ,VISIT_DETAIL_ID  
    ,CONDITION_SOURCE_VALUE 
    ,CONDITION_SOURCE_CONCEPT_ID   
    ,CONDITION_STATUS_SOURCE_VALUE 
FROM TRM.CONDITION_OCCURRENCE;
GO


-- POPULATE CDM.DRUG_EXPOSURE WITH TRM.DRUG_EXPOSURE
TRUNCATE TABLE CDM.DRUG_EXPOSURE;
INSERT INTO CDM.DRUG_EXPOSURE
SELECT 
    DRUG_EXPOSURE_ID   
    ,PERSON_ID   
    ,DRUG_CONCEPT_ID   
    ,DRUG_EXPOSURE_START_DATE  
    ,DRUG_EXPOSURE_START_DATETIME   
    ,DRUG_EXPOSURE_END_DATE 
    ,DRUG_EXPOSURE_END_DATETIME   
    ,VERBATIM_END_DATE 
    ,DRUG_TYPE_CONCEPT_ID   
    ,STOP_REASON 
    ,REFILLS  
    ,QUANTITY  
    ,DAYS_SUPPLY  
    ,SIG 
    ,ROUTE_CONCEPT_ID   
    ,LOT_NUMBER 
    ,PROVIDER_ID  
    ,VISIT_OCCURRENCE_ID  
    ,VISIT_DETAIL_ID  
    ,DRUG_SOURCE_VALUE 
    ,DRUG_SOURCE_CONCEPT_ID   
    ,ROUTE_SOURCE_VALUE 
    ,DOSE_UNIT_SOURCE_VALUE
FROM TRM.DRUG_EXPOSURE;
GO


-- POPULATE CDM.DEVICE_EXPOSURE WITH TRM.DEVICE_EXPOSURE
TRUNCATE TABLE CDM.DEVICE_EXPOSURE;
INSERT INTO CDM.DEVICE_EXPOSURE
SELECT 
    DEVICE_EXPOSURE_ID   
    ,PERSON_ID   
    ,DEVICE_CONCEPT_ID   
    ,DEVICE_EXPOSURE_START_DATE 
    ,DEVICE_EXPOSURE_START_DATETIME   
    ,DEVICE_EXPOSURE_END_DATE 
    ,DEVICE_EXPOSURE_END_DATETIME  
    ,DEVICE_TYPE_CONCEPT_ID   
    ,UNIQUE_DEVICE_ID
    ,QUANTITY  
    ,PROVIDER_ID  
    ,VISIT_OCCURRENCE_ID  
    ,VISIT_DETAIL_ID  
    ,DEVICE_SOURCE_VALUE 
    ,DEVICE_SOURCE_CONCEPT_ID   
FROM TRM.DEVICE_EXPOSURE;
GO 



