
/*
STAGE THE MC TABLE

DEPENDENCIES:
    STG.PATKEY_LIST
    RAW.MC


RESULT:
    CREATION OF STG.MC


NOTES:

WE WILL NOT INCLUDE PATIENT VARIABLE SINCE WE SHOULD HAVE THOSE ON ME
WE WILL NOT INCLUDE ICD PROCEDURE OR ICD DX CODES SINCE WE HAVE TRANSPOSED THOSE FROM
WIDE TO LONG FORMAT
ALL OTHER VARIABLES WILL BE STAGED, CONVERTED TO THE CORRECT TYPES
ONLY FINAL CLAIMS WILL BE STAGED (USING THE CLAIM CONSOLIDATION TABLE)
ROWS WITH NEGATIVE COSTS WILL BE DROPPED, ZERO COSTS WILL BE KEPT

------- VARIABLES TO BE STAGED -------
MC005_LINE
MC005A_VER
MC011_REL
MC012_GENDER
MC014_PATCITY
MC015_PATST
MC016_PATZIP
MC017_PDATE
MC018_ADMDAT
MC019_ADMHR
MC020_ADMTYPE
MC021_ADMSR
MC022_DISHR
MC023_PTDIS
MC036_BILLTYPE
MC037_FACTYPE
MC038_STATUS
MC054_REV
MC055_CPT
MC056_MOD1
MC057_MOD2
MC057A_MOD3
MC057B_MOD4
MC058_OP
MC059_FDATE
MC060_LDATE
MC061_QTY
MC063_TPAY
MC064_PREPAID
MC065_COPAY
MC066_COINS
MC067_DED
MC069_DISDAT
MC071_DRG
MC072_DRGVER
MC073_APC
MC074_APCVER
MC075_NDC
MC076_BILLPRVIDN
MC077_NPI
MC078_PRVLNAME
MC899_RECTYPE
MC902_IDN
MC905_MEDICARE
MC906_FILEID
MC907_MHDO_CLAIM
MC908_MHDO_SUBSSN
MC909_MHDO_CONTRACT
MC910_MHDO_MEMSSN
MC911_MHDO_MEMBERID
MC912_PRVIDN
MC913_MHDO_PRODUCT
MC915_PAID_YR
MC916_PAID_MON
MC917_INCURRED_YR
MC918_INCURRED_MON
MC919_PAID_QTR
MC920_INCURRED_QTR
MC108_ATT_NPI
MC109_ATT_FNAME
MC110_ATT_MNAME
MC111_ATT_LNAME
MC113_ATT_PRVSPEC
MC115_OP_NPI
MC116_OP_FNAME
MC117_OP_MNAME
MC118_OP_LNAME
MC121_RFR_NPI
MC122_RFR_FNAME
MC123_RFR_MNAME
MC124_RFR_LNAME
MC950_SERVICING_NPI

INITIAL DATA CLEANING WILL BE ADDED TO THIS SCRIPT AS NEEDED

-- CHECK THAT PAID AMOUNTS ARE NOT NULL
-- SELECT COUNT(*) FROM RAW.MC WHERE MC063_TPAY IS NULL
*/


-- CREATE A TEMP TABLE WITH SUBSET OF MEDICAL CLIAMS
-- SHOULD PROBABLY NOT REPEAT THIS WORK SINCE WE DO IT FOR STG.ME
-- ALSO PERHAPS ANOTHER CTE WOULD BE BETTER
-- OR AN IF-ELSE CONSTRUCT THAT IGNORES THE FILTERNING WHEN THE NUMBER OF PATIENTS IS MORE THAN THE TOTAL NUMBER OF PATIENTS IN THE DATA
DROP TABLE IF EXISTS ##MC_SAMPLE;
SELECT *
INTO ##MC_SAMPLE
FROM RAW.MC
WHERE MC911_MHDO_MEMBERID IN(SELECT PATKEY_CHR FROM STG.PATKEY_LIST);
-- THIS STEP TAKES A LONG TIME -- MAYBE AN INDEX WOULD HELP.
-- SELECT TOP 10 * FROM ##MC_SAMPLE;
-- SELECT COUNT(*) FROM ##MC_SAMPLE;
-- SELECT TOP 10 * FROM RAW.MC_FILEID_PAYERTYPE;
GO

-- LOAD DATA INTO STG.MC
DROP TABLE IF EXISTS STG.MC;
WITH T0 AS(
    SELECT A.*, B.PAYER_TYPE
    FROM ##MC_SAMPLE A
    LEFT JOIN RAW.MC_FILEID_PAYERTYPE B
    ON A.MC906_FILEID = B.MC906_FILEID
)
,T1 AS(
    SELECT
         CAST(MC005_LINE                        AS INT)             AS LINE
        ,CAST(MC005A_VER                        AS INT)             AS VER
        ,CAST(MC011_REL                         AS VARCHAR(2))      AS REL
        ,CAST(MC012_GENDER                      AS VARCHAR(2))      AS GENDER
        ,CAST(MC014_PATCITY                     AS VARCHAR(30))     AS PATCITY
        ,CAST(MC015_PATST                       AS VARCHAR(5))      AS PATST
        ,CAST(MC016_PATZIP                      AS VARCHAR(10))     AS PATZIP
        ,CAST(MC017_PDATE                       AS DATE)            AS PDATE
        ,CAST(MC018_ADMDAT                      AS DATE)            AS ADMDAT
        ,CAST(MC019_ADMHR                       AS SMALLINT)        AS ADMHR
        ,CAST(MC020_ADMTYPE                     AS VARCHAR(10))     AS ADMTYPE
        ,CAST(TRIM(UPPER(MC021_ADMSR))          AS VARCHAR(10))     AS ADMSR
        ,CAST(MC022_DISHR                       AS SMALLINT)        AS DISHR
        ,CAST(TRIM(UPPER(MC023_PTDIS))          AS VARCHAR(10))     AS PTDIS
        ,CAST(MC036_BILLTYPE                    AS VARCHAR(10))     AS BILLTYPE
        ,CAST(MC037_FACTYPE                     AS VARCHAR(10))     AS FACTYPE
        ,CAST(MC038_STATUS                      AS VARCHAR(10))     AS STATUS
        ,CAST(MC054_REV                         AS VARCHAR(10))     AS REV
        ,CAST(MC055_CPT                         AS VARCHAR(10))     AS CPT
        ,CAST(MC056_MOD1                        AS VARCHAR(4))      AS MOD1
        ,CAST(MC057_MOD2                        AS VARCHAR(4))      AS MOD2
        ,CAST(MC057A_MOD3                       AS VARCHAR(4))      AS MOD3
        ,CAST(MC057B_MOD4                       AS VARCHAR(4))      AS MOD4
        ,CAST(MC058_OP                          AS VARCHAR(10))     AS OP
        ,CAST(MC059_FDATE                       AS DATE)            AS FDATE
        ,CAST(MC060_LDATE                       AS DATE)            AS LDATE
        ,CAST(MC061_QTY                         AS INT)             AS QTY
        ,CAST(MC063_TPAY                        AS MONEY)           AS TPAY
        ,CAST(MC064_PREPAID                     AS MONEY)           AS PREPAID
        ,CAST(MC065_COPAY                       AS MONEY)           AS COPAY
        ,CAST(MC066_COINS                       AS MONEY)           AS COINS
        ,CAST(MC067_DED                         AS MONEY)           AS DED
        ,CAST(MC069_DISDAT                      AS DATE)            AS DISDAT
        ,CAST(MC071_DRG                         AS VARCHAR(10))     AS DRG
        ,CAST(MC072_DRGVER                      AS VARCHAR(10))     AS DRGVER
        ,CAST(MC073_APC                         AS VARCHAR(10))     AS APC
        ,CAST(MC074_APCVER                      AS VARCHAR(10))     AS APCVER
        ,CAST(MC075_NDC                         AS VARCHAR(11))     AS NDC
        ,CAST(MC076_BILLPRVIDN                  AS VARCHAR(10))     AS BILLPRVIDN
        ,CAST(MC077_NPI                         AS VARCHAR(10))     AS NPI
        ,CAST(TRIM(UPPER(MC078_PRVLNAME))       AS VARCHAR(60))     AS PRVLNAME
        ,CAST(MC899_RECTYPE                     AS VARCHAR(5))      AS RECTYPE
        ,CAST(MC901_AGE                         AS SMALLINT)        AS AGE
        ,CAST(MC902_IDN                         AS BIGINT)          AS IDN
        ,CAST(MC905_MEDICARE                    AS VARCHAR(5))      AS MEDICARE
        ,CAST(MC907_MHDO_CLAIM                  AS BIGINT)          AS MHDO_CLAIM
        ,CAST(MC911_MHDO_MEMBERID               AS BIGINT)          AS PATKEY
        ,CAST(MC912_PRVIDN                      AS VARCHAR(10))     AS PRVIDN
        ,CAST(MC913_MHDO_PRODUCT                AS VARCHAR(10))     AS MHDO_PRODUCT
        ,CAST(MC915_PAID_YR                     AS SMALLINT)        AS PAID_YR
        ,CAST(MC916_PAID_MON                    AS SMALLINT)        AS PAID_MON
        ,CAST(MC917_INCURRED_YR                 AS SMALLINT)        AS INCURRED_YR
        ,CAST(MC918_INCURRED_MON                AS SMALLINT)        AS INCURRED_MON
        ,CAST(MC919_PAID_QTR                    AS SMALLINT)        AS PAID_QTR
        ,CAST(MC920_INCURRED_QTR                AS SMALLINT)        AS INCURRED_QTR
        ,CAST(MC108_ATT_NPI                     AS VARCHAR(20))     AS ATT_NPI
        ,CAST(MC109_ATT_FNAME                   AS VARCHAR(60))     AS ATT_FNAME
        ,CAST(MC110_ATT_MNAME                   AS VARCHAR(60))     AS ATT_MNAME
        ,CAST(MC111_ATT_LNAME                   AS VARCHAR(60))     AS ATT_LNAME
        ,CAST(MC113_ATT_PRVSPEC                 AS VARCHAR(60))     AS ATT_PRVSPEC
        ,CAST(MC115_OP_NPI                      AS VARCHAR(20))     AS OP_NPI
        ,CAST(MC116_OP_FNAME                    AS VARCHAR(60))     AS OP_FNAME
        ,CAST(MC117_OP_MNAME                    AS VARCHAR(60))     AS OP_MNAME
        ,CAST(MC118_OP_LNAME                    AS VARCHAR(60))     AS OP_LNAME
        ,CAST(MC121_RFR_NPI                     AS VARCHAR(20))     AS RFR_NPI
        ,CAST(MC122_RFR_FNAME                   AS VARCHAR(60))     AS RFR_FNAME
        ,CAST(MC123_RFR_MNAME                   AS VARCHAR(60))     AS RFR_MNAME
        ,CAST(MC124_RFR_LNAME                   AS VARCHAR(60))     AS RFR_LNAME
        ,CAST(MC950_SERVICING_NPI               AS VARCHAR(20))     AS SERVICING_NPI
        ,CAST(PAYER_TYPE                        AS VARCHAR(20))     AS PAYER_TYPE
    FROM T0
    -- FROM RAW.MC
        -- ,CAST(MC908_MHDO_SUBSSN     AS VARCHAR(10))     AS MHDO_SUBSSN
        -- ,CAST(MC909_MHDO_CONTRACT   AS VARCHAR(10))     AS MHDO_CONTRACT
        -- ,CAST(MC910_MHDO_MEMSSN     AS VARCHAR(10))     AS MHDO_MEMSSN
        -- ,CAST(MC906_FILEID          AS VARCHAR(10))     AS FILEID
)
,T2 AS (
    SELECT A.*
    FROM T1 A
    INNER JOIN RAW.MC_CLAIM_CONSOLIDATION B
        ON A.MHDO_CLAIM = B.MC907_MHDO_CLAIM AND A.IDN = B.MC902_IDN
    WHERE
        A.STATUS IN('1','01','19', '2','02','20', '21', '04', '4') AND
        -- TPAY >= 0 AND
        A.PATKEY IS NOT NULL AND
        A.MHDO_CLAIM IS NOT NULL
-- CLAIM STATUS SHOULD BE ONE OF
-- 1: PRIMARY
-- 19: PRIMARY -FORWARDED TO ADDITIONAL PAYERS
-- 2: SECONDARY
-- 20: SECONDARY - FORWARDED TO ADDTIONAL PAYERS
-- 4: DENIED
-- 21: TERTIARY-FORWARDED (VERY SMALL NUMBER)

-- OTHER STATUS TYPES THAT ARE EXCLUDED ARE
-- 22: REVERSAL
-- NULL (SHOULD WE EXCLUDE NULLS?)
)
SELECT *
INTO STG.MC
FROM T2;
GO

-- DROP TEMP TABLES
DROP TABLE IF EXISTS ##MC_SAMPLE;
GO

/*
WE ALSO MIGHT CHECK THAT MHDO_CLAIM AND LINE NUMBER UNIQUELY IDENTIFY A ROW IN STG.MC
WE MIGHT WANT TO ENFORCE THIS CONSTRAINT SINCE IT SHOULD IN THEORY BE TRUE.
HOWEVER WE NEED A METHOD TO HANDLE THE EDGE CASES WHEN IT IS NOT TRUE

WE SHOULD ALSO NEED TO MAKE SURE THAT A CLAIM HAS ONE AND ONLY ONE PATIENT
WE NEED A METHOD FOR FIXING THIS WHEN THERE IS MORE THAN ONE PATIENT ON A CLAIM

-- SELECT TOP 100 * FROM STG.MC;
-- SELECT COUNT(*) FROM STG.MC;
*/
