/*
CREATE THE LONG ICD PROCEDURE DATASET

DEPENDENCIES:
  RAW.MC
  STG.MC

RESULT:
  STG.ICD_PROC TABLE

THIS IS VERY SIMILAR TO THE LONG ICD_PROC DATASET
ICD PROCEDURE CODES ARE ASSUMED TO BE AT THE HEADER LEVEL
THE APCD HAS 24 FIELDS FOR ICD 10 PROCEDURE CODES AND ONE ICD 9 PROCEDURE CODE

------------------------------------------------------------------------------------
ICD PROCEDURE CODE VARIABLES 
MC302_PRNPRCDRCD
MC303_OTHPRCDRCD1
MC304_OTHPRCDRCD2
MC305_OTHPRCDRCD3
MC306_OTHPRCDRCD4
MC307_OTHPRCDRCD5
MC308_OTHPRCDRCD6
MC309_OTHPRCDRCD7
MC310_OTHPRCDRCD8
MC311_OTHPRCDRCD9
MC312_OTHPRCDRCD10
MC313_OTHPRCDRCD11
MC314_OTHPRCDRCD12
MC315_OTHPRCDRCD13
MC316_OTHPRCDRCD14
MC317_OTHPRCDRCD15
MC318_OTHPRCDRCD16
MC319_OTHPRCDRCD17
MC320_OTHPRCDRCD18
MC321_OTHPRCDRCD19
MC322_OTHPRCDRCD20
MC323_OTHPRCDRCD21
MC324_OTHPRCDRCD22
MC325_OTHPRCDRCD23
MC326_OTHPRCDRCD24
MC058_OP -- ICD 9 PRIMARY PROCEDURE CODE (USUALLY A SURGERY I THINK)
*/

-- DDL FOR STG.ICD_PROC
DROP TABLE IF EXISTS STG.ICD_PROC;
CREATE TABLE STG.ICD_PROC(
        PATKEY INT
        ,MHDO_CLAIM INT
        ,VOCABULARY VARCHAR(20)
        ,ICD_PROC VARCHAR(10)
        ,PRIMARY_FLAG BIT
    )
;
GO

-- INSERT TRANSPOSED ICD PROCEDURE CODES INTO LONG STG.ICD_PROC TABLE
-- ONLY INCLUDE PROCEDURE DATA FROM FINAL CLAIMS WHICH WERE DEFINED IN STG.MC
WITH 
MC_SOURCE AS(
  SELECT A.* 
  FROM RAW.MC A
  INNER JOIN STG.MC B
  ON A.MC902_IDN = B.IDN
)
,ICD9_PROC AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD9Proc' AS VOCABULARY
  ,MC058_OP AS ICD_PROC
  ,CAST(1 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC058_OP IS NOT NULL 
)
,PRNPRCDRCD AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC302_PRNPRCDRCD AS ICD_PROC
  ,CAST(1 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC302_PRNPRCDRCD IS NOT NULL 
)
,OTHPRCDRCD1 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC303_OTHPRCDRCD1 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC303_OTHPRCDRCD1 IS NOT NULL 
)
,OTHPRCDRCD2 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC304_OTHPRCDRCD2 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC304_OTHPRCDRCD2 IS NOT NULL 
)
,OTHPRCDRCD3 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC305_OTHPRCDRCD3 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC305_OTHPRCDRCD3 IS NOT NULL 
)
,OTHPRCDRCD4 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC306_OTHPRCDRCD4 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC306_OTHPRCDRCD4 IS NOT NULL 
)
,OTHPRCDRCD5 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC307_OTHPRCDRCD5 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC307_OTHPRCDRCD5 IS NOT NULL 
)
,OTHPRCDRCD6 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC308_OTHPRCDRCD6 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC308_OTHPRCDRCD6 IS NOT NULL 
)
,OTHPRCDRCD7 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC309_OTHPRCDRCD7 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC309_OTHPRCDRCD7 IS NOT NULL 
)
,OTHPRCDRCD8 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC310_OTHPRCDRCD8 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC310_OTHPRCDRCD8 IS NOT NULL 
)
,OTHPRCDRCD9 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC311_OTHPRCDRCD9 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC311_OTHPRCDRCD9 IS NOT NULL 
)
,OTHPRCDRCD10 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC312_OTHPRCDRCD10 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC312_OTHPRCDRCD10 IS NOT NULL 
)
,OTHPRCDRCD11 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC313_OTHPRCDRCD11 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC313_OTHPRCDRCD11 IS NOT NULL 
)
,OTHPRCDRCD12 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC314_OTHPRCDRCD12 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC314_OTHPRCDRCD12 IS NOT NULL 
)
,OTHPRCDRCD13 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC315_OTHPRCDRCD13 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC315_OTHPRCDRCD13 IS NOT NULL 
)
,OTHPRCDRCD14 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC316_OTHPRCDRCD14 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC316_OTHPRCDRCD14 IS NOT NULL 
)
,OTHPRCDRCD15 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC317_OTHPRCDRCD15 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC317_OTHPRCDRCD15 IS NOT NULL 
)
,OTHPRCDRCD16 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC318_OTHPRCDRCD16 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC318_OTHPRCDRCD16 IS NOT NULL 
)
,OTHPRCDRCD17 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC319_OTHPRCDRCD17 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC319_OTHPRCDRCD17 IS NOT NULL 
)
,OTHPRCDRCD18 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC320_OTHPRCDRCD18 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC320_OTHPRCDRCD18 IS NOT NULL 
)
,OTHPRCDRCD19 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC321_OTHPRCDRCD19 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC321_OTHPRCDRCD19 IS NOT NULL 
)
,OTHPRCDRCD20 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC322_OTHPRCDRCD20 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC322_OTHPRCDRCD20 IS NOT NULL 
)
,OTHPRCDRCD21 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC323_OTHPRCDRCD21 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC323_OTHPRCDRCD21 IS NOT NULL 
)
,OTHPRCDRCD22 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC324_OTHPRCDRCD22 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC324_OTHPRCDRCD22 IS NOT NULL 
)
,OTHPRCDRCD23 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC325_OTHPRCDRCD23 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC325_OTHPRCDRCD23 IS NOT NULL 
)
,OTHPRCDRCD24 AS(
  SELECT DISTINCT
  CAST(MC907_MHDO_CLAIM AS INT) AS MHDO_CLAIM
  ,'ICD10PCS' AS VOCABULARY
  ,MC326_OTHPRCDRCD24 AS ICD_PROC
  ,CAST(0 AS BIT) AS PRIMARY_FLAG
  FROM MC_SOURCE
  WHERE MC326_OTHPRCDRCD24 IS NOT NULL 
)
,COMBINED AS(
SELECT * FROM ICD9_PROC    UNION
SELECT * FROM PRNPRCDRCD   UNION
SELECT * FROM OTHPRCDRCD1  UNION
SELECT * FROM OTHPRCDRCD2  UNION
SELECT * FROM OTHPRCDRCD3  UNION
SELECT * FROM OTHPRCDRCD4  UNION
SELECT * FROM OTHPRCDRCD5  UNION
SELECT * FROM OTHPRCDRCD6  UNION
SELECT * FROM OTHPRCDRCD7  UNION
SELECT * FROM OTHPRCDRCD8  UNION
SELECT * FROM OTHPRCDRCD9  UNION
SELECT * FROM OTHPRCDRCD10 UNION
SELECT * FROM OTHPRCDRCD11 UNION
SELECT * FROM OTHPRCDRCD12 UNION
SELECT * FROM OTHPRCDRCD13 UNION
SELECT * FROM OTHPRCDRCD14 UNION
SELECT * FROM OTHPRCDRCD15 UNION
SELECT * FROM OTHPRCDRCD16 UNION
SELECT * FROM OTHPRCDRCD17 UNION
SELECT * FROM OTHPRCDRCD18 UNION
SELECT * FROM OTHPRCDRCD19 UNION
SELECT * FROM OTHPRCDRCD20 UNION
SELECT * FROM OTHPRCDRCD21 UNION
SELECT * FROM OTHPRCDRCD22 UNION
SELECT * FROM OTHPRCDRCD23 UNION
SELECT * FROM OTHPRCDRCD24 
)
,WITH_PATKEY AS(
  SELECT B.PATKEY, A.*
  FROM COMBINED A 
  INNER JOIN (SELECT DISTINCT MHDO_CLAIM, PATKEY FROM STG.MC) B 
  ON A.MHDO_CLAIM = B.MHDO_CLAIM
)
INSERT INTO STG.ICD_PROC WITH (TABLOCK)
    (PATKEY, MHDO_CLAIM, VOCABULARY, ICD_PROC, PRIMARY_FLAG)
SELECT PATKEY, MHDO_CLAIM, VOCABULARY, ICD_PROC, PRIMARY_FLAG
FROM WITH_PATKEY;
GO

/*
-- SELECT COUNT(*) FROM STG.ICD_PROC;
-- SELECT TOP 100 * FROM STG.ICD_PROC;
*/
