/*
STAGE THE PHARMACY CLAIM DATA 

PHARMACY CLAIM VARIABLES ARE:
PC005_LINE
PC011_REL
PC012_GENDER
PC014_PATCITY
PC015_PATST
PC016_PATZIP
PC017_PDATE
PC025_STATUS
PC026_NDC
PC027_DRUGNM
PC028_NEWPR
PC029_GENRX
PC030_DAW
PC031_COMPOUND
PC032_FDATE
PC033_QTY
PC034_DAYS
PC036_TPAY
PC037_INGRED
PC038_POSTAGE
PC039_DISPFEE
PC040_COPAY
PC041_COINS
PC042_DED
PC043_PTNPYAMT
PC899_RECTYPE
PC901_AGE
PC902_IDN
PC905_FILEID
PC906_MHDO_CLAIM
PC907_MHDO_SUBSSN
PC908_MHDO_CONTRACT
PC909_MHDO_MEMSSN
PC910_MHDO_MEMBERID
PC911_MHDO_GENDER
PC912_MHDO_PRODUCT
PC913_PHARMID
PC914_PAID_YR
PC915_PAID_MON
PC916_INCURRED_YR
PC917_INCURRED_MON
PC918_PAID_QTR
PC919_INCURRED_QTR
PC920_DEA_PRVIDN
PC950_PRESCRIBING_NPI
PC955_COUNTY_FIPS

*/

-- PUT PHARMACY CLAIMS INTO A TEMP TABLE FOR TRANSFORMATION
DROP TABLE IF EXISTS ##PC_SAMPLE;
SELECT *
INTO ##PC_SAMPLE
FROM RAW.PC
WHERE PC910_MHDO_MEMBERID IN(SELECT PATKEY_CHR FROM STG.PATKEY_LIST);
GO


-- LOAD DATA INTO STG.PC
DROP TABLE IF EXISTS STG.PC;
WITH T0 AS(
    SELECT A.*, B.PAYER_TYPE
    FROM ##PC_SAMPLE A
    LEFT JOIN RAW.PC_FILEID_PAYERTYPE B
    ON A.PC905_FILEID = B.PC905_FILEID
)

SELECT 
    CAST(PC005_LINE             AS INT)             AS LINE
    ,CAST(PC011_REL             AS VARCHAR(5))      AS REL
    ,CAST(PC012_GENDER          AS VARCHAR(5))      AS GENDER
    ,CAST(PC014_PATCITY         AS VARCHAR(30))     AS PATCITY
    ,CAST(PC015_PATST           AS VARCHAR(5))      AS PATST
    ,CAST(PC016_PATZIP          AS VARCHAR(10))     AS PATZIP 
    ,CAST(PC017_PDATE           AS DATE)            AS PDATE 
    ,CAST(PC025_STATUS          AS VARCHAR(10))     AS STATUS
    ,CAST(PC026_NDC             AS VARCHAR(11))     AS NDC 
    ,CAST(PC027_DRUGNM          AS VARCHAR(80))     AS DRUGNM
    ,CAST(PC028_NEWPR           AS VARCHAR(5))      AS NEWPR
    ,CAST(PC029_GENRX           AS VARCHAR(5))      AS GENRX
    ,CAST(PC030_DAW             AS VARCHAR(5))      AS DAW
    ,CAST(PC031_COMPOUND        AS VARCHAR(5))      AS COMPOUND
    ,CAST(PC032_FDATE           AS DATE)            AS FDATE
    ,CAST(PC033_QTY             AS INTEGER)         AS QTY 
    ,CAST(PC034_DAYS            AS INTEGER)         AS DAYS 
    ,CAST(PC036_TPAY            AS MONEY)           AS TPAY 
    ,CAST(PC037_INGRED          AS MONEY)           AS INGRED 
    ,CAST(PC038_POSTAGE         AS MONEY)           AS POSTAGE
    ,CAST(PC039_DISPFEE         AS MONEY)           AS DISPFEE
    ,CAST(PC040_COPAY           AS MONEY)           AS COPAY 
    ,CAST(PC041_COINS           AS MONEY)           AS COINS 
    ,CAST(PC042_DED             AS MONEY)           AS DED 
    ,CAST(PC043_PTNPYAMT        AS MONEY)           AS PTNPYAMT
    ,CAST(PC899_RECTYPE         AS VARCHAR(5))      AS RECTYPE
    ,CAST(PC901_AGE             AS SMALLINT)        AS AGE
    ,CAST(PC902_IDN             AS BIGINT)          AS IDN
    -- PC905_FILEID          
    ,CAST(PC906_MHDO_CLAIM      AS BIGINT)          AS MHDO_CLAIM 
    -- PC907_MHDO_SUBSSN
    -- PC908_MHDO_CONTRACT
    -- PC909_MHDO_MEMSSN
    ,CAST(PC910_MHDO_MEMBERID   AS BIGINT)          AS PATKEY
    ,CAST(PC911_MHDO_GENDER     AS VARCHAR(5))      AS MHDO_GENDER
    ,CAST(PC912_MHDO_PRODUCT    AS VARCHAR(10))     AS MHDO_PRODUCT
    ,CAST(PC913_PHARMID         AS BIGINT)          AS PHARMID 
    ,CAST(PC914_PAID_YR         AS SMALLINT)        AS PAID_YR
    ,CAST(PC915_PAID_MON        AS SMALLINT)        AS PAID_MON 
    ,CAST(PC916_INCURRED_YR     AS SMALLINT)        AS INCURRED_YR
    ,CAST(PC917_INCURRED_MON    AS SMALLINT)        AS INCURRED_MON 
    ,CAST(PC918_PAID_QTR        AS SMALLINT)        AS PAID_QTR 
    ,CAST(PC919_INCURRED_QTR    AS SMALLINT)        AS INCURRED_QTR
    ,CAST(PC920_DEA_PRVIDN      AS VARCHAR(20))     AS DEA_PRVIDN
    ,CAST(PC950_PRESCRIBING_NPI AS VARCHAR(20))     AS PRESCRIBING_NPI 
    -- PC955_COUNTY_FIPS    
INTO STG.PC
FROM T0
WHERE
    PC025_STATUS IN('1','01','19', '2','02','20', '21', '04', '4') AND
    -- TPAY >= 0 AND -- SHOULD WE EXCLUDE CALIMS BASED ON NEGATIVE PAID AMOUNTS?
    PC910_MHDO_MEMBERID IS NOT NULL AND
    PC906_MHDO_CLAIM IS NOT NULL
;
GO

/*
-- CLAIM STATUS SHOULD BE ONE OF
-- 1: PRIMARY
-- 19: PRIMARY -FORWARDED TO ADDITIONAL PAYERS
-- 2: SECONDARY
-- 20: SECONDARY - FORWARDED TO ADDTIONAL PAYERS
-- 4: DENIED
-- 21: TERTIARY-FORWARDED (VERY SMALL NUMBER)

-- OTHER STATUS TYPES THAT ARE EXCLUDED ARE
-- 22: REVERSAL
-- NULL (SHOULD WE EXCLUDE NULLS?)
*/

/* CHECK THAT ROW COUNTS ARE SIMILAR
SELECT COUNT(*) FROM ##PC_SAMPLE
SELECT COUNT(*) FROM STG.PC;

*/

-- DROP TEMP TABLES
DROP TABLE IF EXISTS ##PC_SAMPLE;
GO


